apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-helm-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bartpaczkows/argocd-poc.git'
    targetRevision: HEAD
    path: helm_app
    helm:
      valueFiles:
      - values_dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ota-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
