apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-helm-prod
  namespace: argocd
spec:
  project: ota-delivery
  source:
    repoURL: 'https://github.com/bartpaczkows/argocd-poc.git'
    targetRevision: HEAD
    path: helm_app
    helm:
      valueFiles:
      - values_prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ota-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
