apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: ota-kustomize
# resources:
# - templates/service.yaml
# - templates/config_map.yaml
# - templates/deployment.yaml



helmGlobals:
  chartHome: ../

helmCharts:
- name: helmapp
  valuesFile: values.yaml
  releaseName: helmapp
  namespace: ota-kustomize
