apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../

helmCharts:
- name: helmapp
  valuesFile: values.yaml
  releaseName: helmapp
  namespace: ota-kustomize
