apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ota-kustomize-stage


helmGlobals:
  chartHome:  ../../base

helmCharts:
- name: helmapp
  valuesFile: values-stage.yaml
  releaseName: helmapp

patchesStrategicMerge:
- map.yaml