apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-kustomize
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bartpaczkows/argocd-poc.git'
    targetRevision: HEAD
    path: kustomize_app/base/helmapp/
  destination:
    server: https://kubernetes.default.svc
    namespace: ota-kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true