apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: ota-kustomize-prod

resources:
- ./mySecret.yaml

configMapGenerator:
- name: generated-configmap
  envs:
  - .env

helmGlobals:
  chartHome:  ../../base

helmCharts:
- name: helmapp
  valuesFile: values-prod.yaml
  releaseName: helmapp


patchesStrategicMerge:
- map.yaml